version: '3.8'
name: traefik

networks:
  default:
    external:
      name: traefik

services:
  traefik:
    image: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.phpmyadmin.address=:9000

      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=${EMAIL_ADMIN}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      
      - --api=true
        
      # enable access logs
      - --accesslog=true
      - --accesslog.filepath=/logs/access.log
    labels:
      - traefik.enable=true

      # Traefik dashboard
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.middlewares.auth.basicauth.users=${BACKEND_AUTH}
      - traefik.http.routers.traefik.middlewares=auth
        
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always